

export const products = [
  {
    title: "women round neck cotton top",
    description: "a lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 4721,
    image: "1",
    category: "women",
    subcategory: "tops",
    sizes: ["S", "M", "L"],
    date: 1716634345448,
    // bestseller: true,
    color: ["red", "blue"],
    stock: 120
  },
  {
    title: "men round neck pure cotton t-shirt",
    description: "a lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 8327,
    image: "2",
    category: "men",
    subcategory: "tops",
    sizes: ["M", "L", "XL"],
    date: 1716621345448,
    // bestseller: true,
    color: ["black", "white", "green"],
    stock: 120
  },
  {
    title: "girls round neck cotton top",
    description: "a lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 5634,
    image: "3",
    category: "kid",
    subcategory: "tops",
    sizes: ["S", "L", "XL"],
    date: 1716234545448,
    // bestseller: true,
    color: ["pink", "yellow"],
    stock: 120
  },
  {
    title: "men round neck pure cotton t-shirt",
    description: "a lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 2999,
    image: "4",
    category: "men",
    subcategory: "tops",
    sizes: ["S", "M", "2Xl"],
    date: 1716621345448,
    // bestseller: true,
    color: ["blue", "grey", "white"],
    stock: 120
  },
  {
    title: "women round neck cotton top",
    description: "a lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 6442,
    image: "5",
    category: "women",
    subcategory: "tops",
    sizes: ["M", "L", "XL"],
    date: 1716622345448,
    // bestseller: true,
    color: ["purple", "black"],
    stock: 120
  },
  {
    title: "girls round neck cotton top",
    description: "a lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 9178,
    image: "6",
    category: "kid",
    subcategory: "tops",
    sizes: ["S", "L", "XL"],
    date: 1716623423448,
    // bestseller: true,
    color: ["red", "green", "yellow"],
    stock: 120
  },
  {
    title: "men tapered fit flat-front trousers",
    description: "a lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 1850,
    image: "7",
    category: "men",
    subcategory: "bottoms",
    sizes: ["S", "L", "XL"],
    date: 1716621542448,
    // bestseller: false,
    color: ["brown", "blue"],
    stock: 120
  },
  {
    title: "men round neck pure cotton t-shirt",
    description: "a lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 7632,
    image: "8",
    category: "men",
    subcategory: "tops",
    sizes: ["S", "M", "L", "XL"],
    date: 1716622345448,
    // bestseller: false,
    color: ["black", "white"],
    stock: 120
  },
  {
    title: "girls round neck cotton top",
    description: "a lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 4120,
    image: "9",
    category: "kid",
    subcategory: "tops",
    sizes: ["M", "L", "XL"],
    date: 1716621235448,
    // bestseller: false,
    color: ["pink", "purple", "yellow"],
    stock: 120
  },
  {
    title: "men tapered fit flat-front trousers",
    description: "a lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 5078,
    image: "10",
    category: "men",
    subcategory: "bottoms",
    sizes: ["S", "L", "XL"],
    date: 1716622235448,
    // bestseller: false,
    color: ["blue", "black", "white"],
    stock: 120
  },
    {
    title: "women round neck cotton top",
    description: "a lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 3120,
    image: "11",
    category: "women",
    subcategory: "tops",
    sizes: ["S", "M", "L"],
    date: 1716621245448,
    // bestseller: false,
    color: ["red", "blue"],
    stock: 120
  },
  {
    title: "men round neck pure cotton t-shirt",
    description: "a lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 6833,
    image: "12",
    category: "men",
    subcategory: "tops",
    sizes: ["M", "L", "XL"],
    date: 1716623345448,
    // bestseller: false,
    color: ["black", "white", "green"],
    stock: 120
  },
  {
    title: "girls round neck cotton top",
    description: "a lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 2750,
    image: "13",
    category: "kid",
    subcategory: "tops",
    sizes: ["S", "L", "XL"],
    date: 1716624445448,
    // bestseller: false,
    color: ["pink", "yellow"],
    stock: 120
  },
  {
    title: "men tapered fit flat-front trousers",
    description: "a lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 7399,
    image: "14",
    category: "men",
    subcategory: "bottoms",
    sizes: ["S", "M", "XL"],
    date: 1716625445448,
    // bestseller: false,
    color: ["blue", "grey"],
    stock: 120
  },
  {
    title: "women round neck cotton top",
    description: "a lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 5580,
    image: "15",
    category: "women",
    subcategory: "tops",
    sizes: ["M", "L", "XL"],
    date: 1716626445448,
    // bestseller: false,
    color: ["purple", "black"],
    stock: 120
  },
  {
    title: "girls round neck cotton top",
    description: "a lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 4890,
    image: "16",
    category: "kid",
    subcategory: "tops",
    sizes: ["S", "M", "L"],
    date: 1716627445448,
    // bestseller: false,
    color: ["red", "green", "yellow"],
    stock: 120
  },
  {
    title: "men round neck pure cotton t-shirt",
    description: "a lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 9420,
    image: "17",
    category: "men",
    subcategory: "tops",
    sizes: ["S", "M", "XXL"],
    date: 1716628445448,
    // bestseller: false,
    color: ["blue", "black", "white"],
    stock: 120
  },
  {
    title: "women round neck cotton top",
    description: "a lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 6399,
    image: "18",
    category: "women",
    subcategory: "tops",
    sizes: ["M", "L", "XL"],
    date: 1716629445448,
    // bestseller: false,
    color: ["purple", "white"],
    stock: 120
  },
  {
    title: "girls round neck cotton top",
    description: "a lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 2850,
    image: "19",
    category: "kid",
    subcategory: "tops",
    sizes: ["S", "L", "XL"],
    date: 1716630445448,
    // bestseller: false,
    color: ["pink", "purple", "yellow"],
    stock: 120
  },
  {
    title: "men tapered fit flat-front trousers",
    description: "a lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 8300,
    image: "20",
    category: "men",
    subcategory: "bottoms",
    sizes: ["S", "M", "XL"],
    date: 1716631445448,
    // bestseller: false,
    color: ["grey", "black", "blue"],
    stock: 120
  },
    {
    title: "women round neck cotton top",
    description: "a lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 4721,
    image: "21",
    category: "women",
    subcategory: "tops",
    sizes: ["S", "M", "L"],
    date: 1716632445448,
    // bestseller: true,
    color: ["red", "blue"],
    stock: 120
  },
  {
    title: "men round neck pure cotton t-shirt",
    description: "a lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 8327,
    image: "22",
    category: "men",
    subcategory: "tops",
    sizes: ["M", "L", "XL"],
    date: 1716633445448,
    // bestseller: true,
    color: ["black", "white", "green"],
    stock: 120
  },
  {
    title: "girls round neck cotton top",
    description: "a lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 5634,
    image: "23",
    category: "kid",
    subcategory: "tops",
    sizes: ["S", "L", "XL"],
    date: 1716634445448,
    // bestseller: true,
    color: ["pink", "yellow"],
    stock: 120
  },
  {
    title: "men round neck pure cotton t-shirt",
    description: "a lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 2999,
    image: "24",
    category: "men",
    subcategory: "tops",
    sizes: ["S", "M", "XXL"],
    date: 1716635445448,
    // bestseller: true,
    color: ["blue", "grey", "white"],
    stock: 120
  },
  {
    title: "women round neck cotton top",
    description: "a lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 6442,
    image: "25",
    category: "women",
    subcategory: "tops",
    sizes: ["M", "L", "XL"],
    date: 1716636445448,
    // bestseller: true,
    color: ["purple", "black"],
    stock: 120
  },
  {
    title: "girls round neck cotton top",
    description: "a lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 9178,
    image: "26",
    category: "kid",
    subcategory: "tops",
    sizes: ["S", "L", "XL"],
    date: 1716637445448,
    // bestseller: true,
    color: ["red", "green", "yellow"],
    stock: 120
  },
  {
    title: "men tapered fit flat-front trousers",
    description: "a lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 1850,
    image: "27",
    category: "men",
    subcategory: "bottoms",
    sizes: ["S", "L", "XL"],
    date: 1716638445448,
    // bestseller: false,
    color: ["brown", "blue"],
    stock: 120
  },
  {
    title: "men round neck pure cotton t-shirt",
    description: "a lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 7632,
    image: "28",
    category: "men",
    subcategory: "tops",
    sizes: ["S", "M", "L", "XL"],
    date: 1716639445448,
    // bestseller: false,
    color: ["black", "white"],
    stock: 120
  },
  {
    title: "girls round neck cotton top",
    description: "a lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 4120,
    image: "29",
    category: "kid",
    subcategory: "tops",
    sizes: ["M", "L", "XL"],
    date: 1716640445448,
    // bestseller: false,
    color: ["pink", "purple", "yellow"],
    stock: 120
  },
  {
    title: "men tapered fit flat-front trousers",
    description: "a lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 5078,
    image: "30",
    category: "men",
    subcategory: "bottoms",
    sizes: ["S", "L", "XL"],
    date: 1716641445448,
    // bestseller: false,
    color: ["blue", "black", "white"],
    stock: 120
  },
    {
    title: "women round neck cotton top",
    description: "a lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 5890,
    image: "31",
    category: "women",
    subcategory: "tops",
    sizes: ["S", "M", "L"],
    date: 1716642445448,
    // bestseller: false,
    color: ["red", "blue", "white"],
    stock: 120
  },
  {
    title: "men round neck pure cotton t-shirt",
    description: "a lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 7330,
    image: "32",
    category: "men",
    subcategory: "tops",
    sizes: ["M", "L", "XL"],
    date: 1716643445448,
    // bestseller: false,
    color: ["black", "white", "green"],
    stock: 120
  },
  {
    title: "girls round neck cotton top",
    description: "a lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 2899,
    image: "33",
    category: "kid",
    subcategory: "tops",
    sizes: ["S", "L", "XL"],
    date: 1716644445448,
    // bestseller: false,
    color: ["pink", "yellow"],
    stock: 120
  },
  {
    title: "men tapered fit flat-front trousers",
    description: "a lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 8450,
    image: "34",
    category: "men",
    subcategory: "bottoms",
    sizes: ["S", "M", "XL"],
    date: 1716645445448,
    // bestseller: false,
    color: ["blue", "grey"],
    stock: 120
  },
  {
    title: "women round neck cotton top",
    description: "a lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 3990,
    image: "35",
    category: "women",
    subcategory: "tops",
    sizes: ["M", "L", "XL"],
    date: 1716646445448,
    // bestseller: false,
    color: ["purple", "black"],
    stock: 120
  },
  {
    title: "girls round neck cotton top",
    description: "a lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 2190,
    image: "36",
    category: "kid",
    subcategory: "tops",
    sizes: ["S", "M", "L"],
    date: 1716647445448,
    // bestseller: false,
    color: ["red", "green", "yellow"],
    stock: 120
  },
  {
    title: "men round neck pure cotton t-shirt",
    description: "a lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 6720,
    image: "37",
    category: "men",
    subcategory: "tops",
    sizes: ["S", "M", "XXL"],
    date: 1716648445448,
    // bestseller: false,
    color: ["blue", "black", "white"],
    stock: 120
  },
  {
    title: "women round neck cotton top",
    description: "a lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 4880,
    image: "38",
    category: "women",
    subcategory: "tops",
    sizes: ["M", "L", "XL"],
    date: 1716649445448,
    // bestseller: false,
    color: ["purple", "white"],
    stock: 120
  },
  {
    title: "girls round neck cotton top",
    description: "a lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 3350,
    image: "39",
    category: "kid",
    subcategory: "tops",
    sizes: ["S", "L", "XL"],
    date: 1716650445448,
    // bestseller: false,
    color: ["pink", "purple", "yellow"],
    stock: 120
  },
  {
    title: "men tapered fit flat-front trousers",
    description: "a lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 9100,
    image: "40",
    category: "men",
    subcategory: "bottoms",
    sizes: ["S", "M", "XL"],
    date: 1716651445448,
    // bestseller: false,
    color: ["grey", "black", "blue"],
    stock: 120
  },
    {
    title: "women round neck cotton top",
    description: "a lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 6150,
    image: "41",
    category: "women",
    subcategory: "tops",
    sizes: ["S", "M", "L"],
    date: 1716652445448,
    // bestseller: false,
    color: ["red", "blue"],
    stock: 120
  },
  {
    title: "men round neck pure cotton t-shirt",
    description: "a lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 8420,
    image: "42",
    category: "men",
    subcategory: "tops",
    sizes: ["M", "L", "XL"],
    date: 1716653445448,
    // bestseller: false,
    color: ["black", "white", "green"],
    stock: 120
  },
  {
    title: "girls round neck cotton top",
    description: "a lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 2990,
    image: "43",
    category: "kid",
    subcategory: "tops",
    sizes: ["S", "L", "XL"],
    date: 1716654445448,
    // bestseller: false,
    color: ["pink", "yellow", "purple"],
    stock: 120
  },
  {
    title: "men tapered fit flat-front trousers",
    description: "a lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 7550,
    image: "44",
    category: "men",
    subcategory: "bottoms",
    sizes: ["S", "M", "XL"],
    date: 1716655445448,
    // bestseller: false,
    color: ["blue", "grey"],
    stock: 120
  },
  {
    title: "women round neck cotton top",
    description: "a lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 4990,
    image: "45",
    category: "women",
    subcategory: "tops",
    sizes: ["M", "L", "XL"],
    date: 1716656445448,
    // bestseller: false,
    color: ["purple", "black"],
    stock: 120
  },
  {
    title: "girls round neck cotton top",
    description: "a lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 2670,
    image: "46",
    category: "kid",
    subcategory: "tops",
    sizes: ["S", "M", "L"],
    date: 1716657445448,
    // bestseller: false,
    color: ["red", "green", "yellow"],
    stock: 120
  },
  {
    title: "men round neck pure cotton t-shirt",
    description: "a lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 6820,
    image: "47",
    category: "men",
    subcategory: "tops",
    sizes: ["S", "M", "XXL"],
    date: 1716658445448,
    // bestseller: false,
    color: ["blue", "black", "white"],
    stock: 120
  },
  {
    title: "women round neck cotton top",
    description: "a lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 4220,
    image: "48",
    category: "women",
    subcategory: "tops",
    sizes: ["M", "L", "XL"],
    date: 1716659445448,
    // bestseller: false,
    color: ["purple", "white"],
    stock: 120
  },
  {
    title: "girls round neck cotton top",
    description: "a lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 3490,
    image: "49",
    category: "kid",
    subcategory: "tops",
    sizes: ["S", "L", "XL"],
    date: 1716660445448,
    // bestseller: false,
    color: ["pink", "purple", "yellow"],
    stock: 120
  },
  {
    title: "men tapered fit flat-front trousers",
    description: "a lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 9250,
    image: "50",
    category: "men",
    subcategory: "bottoms",
    sizes: ["S", "M", "XL"],
    date: 1716661445448,
    // bestseller: false,
    color: ["grey", "black", "blue"],
    stock: 120
  },



];

    export default products
